name: Check pull requests

on:
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    path: koalaplot-samples

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'corretto'
                    cache: 'gradle'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Checkout koalaplot-core
                uses: actions/checkout@v4
                with:
                    repository: koalaplot/koalaplot-core
                    path: koalaplot-core

            -   name: Publish koalaplot-core to Maven Local
                run: ./gradlew check publishToMavenLocal
                working-directory: koalaplot-core

            -   name: Check koalaplot-samples
                run: ./gradlew check
                working-directory: koalaplot-samples
